sonar.projectKey=dispute-factored-hackathon_dispute-factored-hackathon
sonar.organization=dispute-factored-hackathon
sonar.sources=visa-dispute-hackathon/dispute_agent
sonar.tests=visa-dispute-hackathon/tests
sonar.python.coverage.reportPaths=visa-dispute-hackathon/coverage.xml
sonar.python.version=3.11,3.12
sonar.sourceEncoding=UTF-8
